### ISSUE TITLE
can you submit this to melpa?

### ISSUE THREAD

**Issue by blaenk** [aaronbieber/fence-edit.el#1]
This looks pretty useful, exactly what I was looking for! Would you be kind enough to submit this to melpa?

Also it'd be nice if you could modify the starting block regex a bit from:

```
"^[ \t]*\\(?:~\\{3,\\}\\|`\\{3,\\}\\)\\(.*\\)\n"
```

To allow an optional space between the delimiters and the language name, a style that is valid and many people use:

```
"^[ \t]*\\(?:~\\{3,\\}\\|`\\{3,\\}\\) ?\\(.*\\)\n"
```

So this should now be able to match this:

``````
``` python
blah
```
``````

Then again I haven't actually used it so it could be that it already does support that.

**Comment by aaronbieber** [comment]
I'll take a look to see if it will work, and I may submit this to MELPA once I feel it's ready. Until then, the regexps are in a customizable variable, so you are free to simply customize them to your liking in your init file (set the value of `fence-edit-blocks`).

**Comment by blaenk** [comment]
Cool! Yeah I'm aware that they're in a `defcustom`, I just figured you might be interested in making that small tweak to better benefit others, but yes I can indeed make the tweak on my end.

Are there things missing that you're thinking about in particular before you think to submit to melpa? IMO you should submit it sooner rather than later so as to get more feedback. It's not like you'll be entered into some iron clad binding contract where everyone will judge your very first release :stuck_out_tongue:

**Comment by aaronbieber** [comment]
This wouldn't be my first submission to MELPA (I think it would be my... Fourth?) so I know what I'm in for... I like to make sure I've documented everything very well and have complied with all of the `flycheck-package` recommendations.

If you want to submit a pull request for adding that optional space that would be just fine, but I can also do it when I get a chance to test it more thoroughly.

I also wanted to add patterns for other popular fenced code formats, such as the one(s) that Github and other platforms/websites support. I don't think that will stop me from submitting it to MELPA, though.

**Comment by blaenk** [comment]
Ah fair enough! Those are definitely worthwhile goals to reach before submitting.

Not sure if it would help any, but perhaps it's worth taking a look at markdown-mode.el which [also detects codeblocks](https://github.com/jrblevin/markdown-mode/blob/e751be38938a6aa4bbadb160adf53a9aa0638924/markdown-mode.el#L1323) in the many ways that commonly occur.

**Comment by aaronbieber** [comment]
Good call, I'll take a peek at that.

**Comment by aaronbieber** [comment]
From my testing so far, the pattern used by `markdown-mode` covers more edge cases for spacing around the language symbol. I need to tweak it to prevent an extra line break from getting into the code block but I think this is a solid option.

A little more testing and I'll have a patch online.

**Comment by blaenk** [comment]
Nice!

**Comment by aaronbieber** [comment]
The pattern request was fixed in c6dc869.

I still haven't submitted this to MELPA, so I'll leave this issue open as a reminder.

**Comment by fiveNinePlusR** [comment]
Any update on submitting this to melpa?

**Comment by aaronbieber** [comment]
Completely lost track of this. I am going to attempt to submit today.

**Comment by aaronbieber** [comment]
Request is up! https://github.com/melpa/melpa/pull/4796

**Comment by fiveNinePlusR** [comment]
Awesome! thanks for that

**Comment by aaronbieber** [comment]
The MELPA team had some good feedback and recommended that I implement this using the edit-indirect package. Unfortunately I don't have time to chase that down just now so I closed the request. 

If you want to take a stab at it, pull requests are always welcome.
