### ISSUE TITLE
Use of symbol for LANG-NAME fails

### ISSUE THREAD

**Issue by ddoherty03** [aaronbieber/fence-edit.el#2]
Aaron,

I often use erubis inside LaTeX files with delimiters for ruby code being:

    {:
        ruby_code_here
    :}

Note there is nothing in the block to indicate the language to use; it should always be ruby.

I added the following to my init.el:

      (require 'fence-edit "fence-edit.el")
      (add-to-list 'fence-edit-blocks '("{:" ":}" ruby))

expecting that it would allow me to call `fence-edit-code-at-point` when the cursor is inside such a block to edit the code in an indirect buffer.

However, the effect was to open the block in `text-mode` which is my default mode.

After changing lines 158 to 159 as follows, I got it to work:

    ((functionp (fence-edit--get-mode-for-lang (symbol-name lang-id)))
    (symbol-name lang-id))))

If I'm reading the document string correctly, I believe this is how it should behave:
    
    If LANG-RULE is a symbol, that symbol is assumed to be a language
    name.

I'm thinking this is a bug, right?

**Comment by aaronbieber** [comment]
I'm digging into this and I believe that you are correct about the misbehavior here. I should have this fixed up shortly.
