### ISSUE TITLE
What license is fence-edit under?

### ISSUE THREAD

**Issue by mmauger** [aaronbieber/fence-edit.el#6]
Since this is elisp, this should be GPLv3+. However, it needs to be explicit in a LICENSE file and a license/copyright notice in the code file itself.

I have a desire to contribute to this project with new integration but will reserve doing so until the licensing is clarified.

Thanks for your work.

**Comment by aaronbieber** [comment]
No worries, this was a bit of a toy project for me and hadn't thought about it or really released it with much fanfare. Happy to place it under GPLv3.
